blank_issues_enabled: false
contact_links:
  - name: 'ğŸ™‹ Ask a question on Tieba'
    url:  'https://tieba.baidu.com/f?kw=mathematica'
    about: 'æ¬¢è¿å»ç™¾åº¦è´´å§è®¨è®ºé—®é¢˜ï¼Œäº¤æµèµ„è®¯ã€‚'
  - name: 'ğŸ’¬ Discuss on Stack Exchange'
    url:  'https://mathematica.stackexchange.com/'
    about: 'Ask and answer questions about Mathematica with people around the world.'
